# Generated by Django 2.0.1 on 2018-01-16 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pilapse_project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('folder', models.CharField(max_length=200)),
                ('keep_images', models.BooleanField(verbose_name='Keep images?')),
                ('brightness', models.IntegerField(verbose_name='Target brightness')),
                ('interval', models.IntegerField(verbose_name='Shot interval in seconds')),
                ('width', models.IntegerField(verbose_name='Image width')),
                ('height', models.IntegerField(verbose_name='Image height')),
                ('maxtime', models.IntegerField(verbose_name='Maximum time in minutes')),
                ('maxshots', models.IntegerField(verbose_name='Maximum shots')),
                ('delta', models.IntegerField(verbose_name='Allowed brightness variance')),
                ('alpha', models.FloatField(verbose_name='Exponential averaging constant for brightness smoothing')),
                ('listen', models.BooleanField(verbose_name='Listen mode?')),
            ],
        ),
        migrations.CreateModel(
            name='timelapser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=200)),
                ('ss', models.IntegerField(verbose_name='Shutter Speed')),
                ('iso', models.IntegerField(verbose_name='ISO')),
                ('lastbr', models.IntegerField(verbose_name='Last shot brightness')),
                ('avgbr', models.IntegerField(verbose_name='Average brightness')),
                ('status', models.CharField(max_length=200)),
                ('shots_taken', models.IntegerField(verbose_name='Shots taken')),
                ('lastshot', models.CharField(max_length=200)),
                ('boot', models.BooleanField(verbose_name='Start on boot?')),
                ('active', models.BooleanField(verbose_name='Tracks whether currently taking photos')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djpilapp.pilapse_project')),
            ],
        ),
    ]
